name: PullRequest / ESlint

# develop 브랜치로 pull request 시 실행
on:
    pull_request:
        branches:
            - develop

env:
    NODE_VERSION: 18

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Install NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Code Checkout
              uses: actions/checkout@v2

            - name: Install Dependencies
              run: npm ci

            - name: Code Linting
              run: npm run lint
